### ISSUE TITLE
Page headers too large on laptop screen

### ISSUE THREAD

**Issue by domhnallmorr** [domhnallmorr/Pitwall_Flet#2]
page.window.height ~= 720 on laptop, headers take up too much of screen

**Comment by felipedemelobarbosa** [comment]
Hello, mate. I have little to no experience in Python and I have bit of knowledge of programming basics. Can I help you out somehow in this app?

**Comment by domhnallmorr** [comment]
> Hello, mate. I have little to no experience in Python and I have bit of knowledge of programming basics. Can I help you out somehow in this app?

Hi. Thanks for getting in touch. If you don't have python experience, the best help right now would be to populate the drivers.txt file to the current year (2024). 

Soon I will need to add a "Chief Designer" role for each team. Similar to the drivers, I will need a text file with chief designers from 1998 to this year included. If interested, you could start creating that file.

**Comment by felipedemelobarbosa** [comment]
Hello. I've pulled an update to drivers.txt, but I think there's a file conflict. If you want, I think it may be better if I could edit it in the project repo, not on my fork.

Also, you can count on me with chiefdesigners.txt,

I will try to learn Python because, after reading the code, I saw how simple it's.
